### ISSUE TITLE
python vehicle_detection_main.py --video video_1_61.mp4 --model faster_rcnn_resnet50_coco_2018_01_28/frozen_inference_graph.pb

### ISSUE THREAD

**Issue by byq-luo** [ManishNarayan/vehicle_counting#1]
python vehicle_detection_main.py --video video_1_61.mp4 --model faster_rcnn_resnet50_coco_2018_01_28/frozen_inference_graph.pb 
Show python stop working！

**Comment by ManishNarayan** [comment]
You need to add a model from the tensor flow model zoo. 
Please check the link in the readme.
